<#
从微软官方图标库抓取操作条要用的图标，生成 src/InkEngine/Icons.Paths.cs。

用法：
    pwsh tools/gen-icons.ps1

为什么走脚本而不是手工贴：
  1. 手画图标（哪怕只是几条线几个圆）看着就不对——圆角、光学校正、
     笔画粗细的一致性都是专业图标库调过的。直接取现成的。
  2. 路径数据很长，手工复制容易漏字符；生成出来的东西可复现。
  3. 顺带把来源和许可证信息写进生成文件的头部。

图标库：https://github.com/microsoft/fluentui-system-icons （MIT License）
这里只取 SVG 里的路径数据，不引入它的任何运行时代码。

上游命名不一定和我们的叫法一样（比如"旋转"有好几个候选名），
所以每个图标给一串候选，取第一个能下载到的。
#>

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$repoRoot = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $repoRoot 'src/InkEngine/Icons.Paths.cs'
$cacheDir = Join-Path ([System.IO.Path]::GetTempPath()) 'fluent-icons'
New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null

# 用 jsDelivr 镜像：raw.githubusercontent.com 在国内网络下经常超时。
$base = 'https://cdn.jsdelivr.net/gh/microsoft/fluentui-system-icons@main/assets'

# 本地用的名字 → 上游图标目录候选（按顺序试）
$icons = [ordered]@{
    'copy'   = @('Copy')
    'delete' = @('Delete')
    'flipH'  = @('Flip Horizontal', 'Flip Horizontal 24', 'Arrow Swap')
    'flipV'  = @('Flip Vertical',   'Flip Vertical 24',   'Arrow Swap')
    'rotate' = @('Arrow Rotate Clockwise', 'Rotate Right', 'Arrow Clockwise', 'Rotate Left')
}

function Get-UpstreamFile([string]$folder, [string]$fileName) {
    $cache = Join-Path $cacheDir ($folder + '_' + $fileName)
    if (Test-Path $cache) { return Get-Content $cache -Raw }

    $segments = @($folder, 'SVG', $fileName) | ForEach-Object { [uri]::EscapeDataString($_) }
    $url = "$base/" + ($segments -join '/')
    for ($attempt = 1; $attempt -le 2; $attempt++) {
        try {
            $text = (Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 20).Content
            Set-Content -Path $cache -Value $text -NoNewline
            return $text
        }
        catch {
            if ($attempt -eq 2) { return $null }
        }
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('// 由 tools/gen-icons.ps1 从微软官方图标库生成，请勿手改。')
[void]$sb.AppendLine('// 来源：https://github.com/microsoft/fluentui-system-icons （MIT License，')
[void]$sb.AppendLine('// Copyright (c) 2020 Microsoft Corporation）')
[void]$sb.AppendLine('// 采用各图标的 24×24 regular 变体，viewBox 都是 0 0 24 24。')
[void]$sb.AppendLine('// 许可证全文见 src/InkEngine/THIRD-PARTY-NOTICES.md。')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace InkEngine;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine('/// 操作条图标的路径数据（SVG path 的 d 字符串，24×24 坐标系）。')
[void]$sb.AppendLine('/// 绘制时由 PathGeometries 解析成 Direct2D 几何并按目标尺寸缩放。')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine('internal static class IconPaths')
[void]$sb.AppendLine('{')

$summary = @()
$used = @{}
foreach ($key in $icons.Keys) {
    $found = $null; $foundName = $null
    foreach ($folder in $icons[$key]) {
        $slug = ($folder -replace ' ', '_').ToLowerInvariant()
        $fileName = "ic_fluent_${slug}_24_regular.svg"
        $svg = Get-UpstreamFile $folder $fileName
        if ($svg) { $found = $svg; $foundName = $folder; break }
    }
    if (-not $found) { throw "$key 的所有候选名都下载失败：$($icons[$key] -join ', ')" }

    $m = [regex]::Matches($found, 'd="([^"]+)"')
    if ($m.Count -eq 0) { throw "$foundName 里没有找到路径数据" }
    $d = ($m | ForEach-Object { $_.Groups[1].Value }) -join ' '

    [void]$sb.AppendLine("    /// <summary>Fluent: $foundName (24 regular)</summary>")
    [void]$sb.AppendLine("    public const string $key =")
    [void]$sb.AppendLine('        "' + $d + '";')
    [void]$sb.AppendLine()

    # 统计用到了哪些 SVG 命令——决定运行时解析器要支持到什么程度
    foreach ($c in [regex]::Matches($d, '[A-Za-z]')) { $used[$c.Value] = $true }
    $summary += ("{0,-8} {1,-32} {2} 字符" -f $key, $foundName, $d.Length)
}

[void]$sb.AppendLine('}')
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($true))

Write-Host "已生成 $outFile"
$summary | ForEach-Object { Write-Host "  $_" }
Write-Host ("出现过的 SVG 命令: " + (($used.Keys | Sort-Object) -join ' '))
