<#
「程序图标 v5」的参考笔：从七家**开源、可商用**的图标库里拉 12 支笔的原始 SVG。

用法：
    pwsh tools/gen-pen-refs.ps1

产出三样：
    tools/design-sheet/PenRefs.g.cs   —— 设计稿出图用的路径数据（自动生成，勿手改）
    design/参考-笔图标/*.svg          —— 原图（给用户直接看、给以后留底）
    design/参考-笔图标/README.md      —— 每个文件的来源与许可证

为什么走脚本：和 tools/gen-ui-icons.ps1 同一条规矩 —— 只取上游 SVG 里的 path 数据，
不引任何运行时代码；下载走 jsDelivr 镜像（国内直连 raw.githubusercontent 经常超时）
并带本地缓存；许可证一条条写进生成物，商用能不能用一眼看得见。

⚠ 两类图要分开对待（生成物里带 Stroked 标记）：
    · **填充型**（Fluent / Material Symbols / Phosphor / Remix / MDI / Bootstrap）：
      形状是"用线画出来的轮廓，再填成一块"，画的时候要用 Fill；
    · **描边型**（Tabler / Lucide / Iconoir）：fill="none" + stroke="currentColor"，
      画的时候要用 Pen，线宽取它们自己的 stroke-width（Tabler/Lucide 是 2、Iconoir 是 1.5）。
   两类混着填/描，出来的东西会差很远（描边型被填了＝一整块黑方，填充型只描边＝一团乱线）。
#>

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$repoRoot = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $repoRoot 'tools/design-sheet/PenRefs.g.cs'
$svgDir = Join-Path $repoRoot 'design/参考-笔图标'
New-Item -ItemType Directory -Force -Path $svgDir | Out-Null
$cacheDir = Join-Path ([System.IO.Path]::GetTempPath()) 'pen-refs'
New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null

# 本地键 → 名字 / 库 / 许可证 / 地址（顺序就是稿子里的排列顺序）
# 许可证都从各家的 package.json 或 LICENSE 里核过（2026-10-01）：Fluent MIT、Lucide ISC，
# 其余（Material Symbols / Tabler / Phosphor / Iconoir / Remix / MDI）都是 MIT 或 Apache-2.0。
$refs = @(
    @{ Key='fluentPen';        Name='Pen';            Lib='Fluent UI System Icons'; Lic='MIT';          Url='https://cdn.jsdelivr.net/gh/microsoft/fluentui-system-icons@main/assets/Pen/SVG/ic_fluent_pen_24_regular.svg' },
    @{ Key='fluentInkStroke';  Name='Ink Stroke';     Lib='Fluent UI System Icons'; Lic='MIT';          Url='https://cdn.jsdelivr.net/gh/microsoft/fluentui-system-icons@main/assets/Ink%20Stroke/SVG/ic_fluent_ink_stroke_24_regular.svg' },
    @{ Key='fluentEdit';       Name='Edit';           Lib='Fluent UI System Icons'; Lic='MIT';          Url='https://cdn.jsdelivr.net/gh/microsoft/fluentui-system-icons@main/assets/Edit/SVG/ic_fluent_edit_24_regular.svg' },
    @{ Key='msInkPen';         Name='ink_pen';        Lib='Material Symbols';       Lic='Apache-2.0';   Url='https://cdn.jsdelivr.net/npm/@material-symbols/svg-400@latest/outlined/ink_pen.svg' },
    @{ Key='msDraw';           Name='draw';           Lib='Material Symbols';       Lic='Apache-2.0';   Url='https://cdn.jsdelivr.net/npm/@material-symbols/svg-400@latest/outlined/draw.svg' },
    @{ Key='tablerBallpen';    Name='ballpen';        Lib='Tabler Icons';           Lic='MIT';          Url='https://cdn.jsdelivr.net/npm/@tabler/icons@latest/icons/outline/ballpen.svg' },
    @{ Key='lucidePenLine';    Name='pen-line';       Lib='Lucide';                 Lic='ISC';          Url='https://cdn.jsdelivr.net/npm/lucide-static@latest/icons/pen-line.svg' },
    @{ Key='lucideHighlighter';Name='highlighter';    Lib='Lucide';                 Lic='ISC';          Url='https://cdn.jsdelivr.net/npm/lucide-static@latest/icons/highlighter.svg' },
    @{ Key='phPencilLine';     Name='pencil-line';    Lib='Phosphor Icons';         Lic='MIT';          Url='https://cdn.jsdelivr.net/npm/@phosphor-icons/core@latest/assets/regular/pencil-line.svg' },
    @{ Key='phPenNib';         Name='pen-nib';        Lib='Phosphor Icons';         Lic='MIT';          Url='https://cdn.jsdelivr.net/npm/@phosphor-icons/core@latest/assets/regular/pen-nib.svg' },
    @{ Key='remixMarkPen';     Name='mark-pen-line';  Lib='Remix Icon';             Lic='Apache-2.0';   Url='https://cdn.jsdelivr.net/npm/remixicon@latest/icons/Design/mark-pen-line.svg' },
    @{ Key='mdiDrawPen';       Name='draw-pen';       Lib='Material Design Icons';  Lic='Apache-2.0';   Url='https://cdn.jsdelivr.net/npm/@mdi/svg@latest/svg/draw-pen.svg' }
)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('// 由 tools/gen-pen-refs.ps1 从七家开源图标库生成，请勿手改。')
[void]$sb.AppendLine('// 用途：设计稿 v5「线条型的笔」的参考图（tools/design-sheet/Sheets15.cs 渲染）。')
[void]$sb.AppendLine('// 每家库的许可证逐个写在 PenRef 上，全部允许商用（MIT / ISC / Apache-2.0）。')
[void]$sb.AppendLine('// Stroked=true 的是描边型（画的时候用 Pen，线宽 StrokeW），false 的是填充型（用 Fill）。')
[void]$sb.AppendLine('// 原图另有一份在 design/参考-笔图标/（带 README 列来源）。')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace DesignSheet;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>一支参考笔：路径数据 ＋ 它该被怎么画（填/描）＋ 出处。</summary>')
[void]$sb.AppendLine('internal readonly record struct PenRef(')
[void]$sb.AppendLine('    string Key, string Name, string Lib, string License,')
[void]$sb.AppendLine('    string Path, string Box, bool Stroked, double StrokeW);')
[void]$sb.AppendLine()
[void]$sb.AppendLine('internal static partial class PenRefs')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    /// <summary>稿子里的排列顺序就是这张表的顺序（先 Fluent，再别家）。</summary>')
[void]$sb.AppendLine('    public static readonly PenRef[] All =')
[void]$sb.AppendLine('    {')

$readme = [System.Text.StringBuilder]::new()
[void]$readme.AppendLine('# 参考笔图标（设计稿 v5 用）')
[void]$readme.AppendLine()
[void]$readme.AppendLine('由 `pwsh tools/gen-pen-refs.ps1` 下载，全部来自**开源、可商用**的图标库。')
[void]$readme.AppendLine('文件是该库的**原始 SVG**（未改动），用途是给程序图标挑一支"线条型"的笔做参考。')
[void]$readme.AppendLine()
[void]$readme.AppendLine('| 文件 | 图标 | 库 | 许可证 | 来源 |')
[void]$readme.AppendLine('|---|---|---|---|---|')

$log = @()
foreach ($r in $refs) {
    $cache = Join-Path $cacheDir ($r.Key + '.svg')
    if (Test-Path $cache) { $svg = Get-Content $cache -Raw }
    else {
        for ($attempt = 1; $attempt -le 4; $attempt++) {
            try { $svg = (Invoke-WebRequest -Uri $r.Url -UseBasicParsing -TimeoutSec 25).Content; break }
            catch {
                if ($attempt -eq 4) { throw "下载失败：$($r.Url)`n$($_.Exception.Message)" }
                Start-Sleep -Seconds 2
            }
        }
        Set-Content -Path $cache -Value $svg -NoNewline
    }

    $box = [regex]::Match($svg, 'viewBox="([^"]+)"').Groups[1].Value
    if (-not $box) { throw "$($r.Key) 没有 viewBox" }

    # 描边型：根节点 fill="none" + stroke="currentColor"（Tabler / Lucide / Iconoir 三家）
    $stroked = ($svg -match '<svg[^>]*fill="none"') -and ($svg -match 'stroke="currentColor"')
    $sw = 0.0
    if ($stroked) {
        $swText = [regex]::Match($svg, 'stroke-width="([^"]+)"').Groups[1].Value
        $sw = if ($swText) { [double]$swText } else { 2.0 }
    }

    # ⚠ 前面那个 (?<=\s) 是必须的：光写 d="..." 会把别的属性的尾巴也匹配进来（gen-ui-icons.ps1 里踩过）
    $m = [regex]::Matches($svg, '(?<=\s)d="([^"]+)"')
    if ($m.Count -eq 0) { throw "$($r.Key) 里没有找到路径数据" }
    # Tabler 的 SVG 第一段固定是一个 24×24 的垫片方框（`M0 0h24v24H0z`），丢掉：
    # 留着它，填充型会被填成一整块黑方、描边型会多出一圈方框。
    $paths = @($m | ForEach-Object { $_.Groups[1].Value } |
               Where-Object { -not ($_.Trim() -match '^M0 0h24v24H0z$') })
    if ($paths.Count -eq 0) { throw "$($r.Key) 只剩垫片那一笔" }
    $d = $paths -join ' '

    $strokedText = if ($stroked) { 'true' } else { 'false' }
    [void]$sb.AppendLine("        // $($r.Lib) · $($r.Name)（$($r.Lic)）$(if ($stroked) { '· 描边型' } else { '· 填充型' })")
    [void]$sb.AppendLine("        new(""$($r.Key)"", ""$($r.Name)"", ""$($r.Lib)"", ""$($r.Lic)"",")
    [void]$sb.AppendLine("            ""$d"", ""$box"", $strokedText, $($sw.ToString([System.Globalization.CultureInfo]::InvariantCulture))),")

    Set-Content -Path (Join-Path $svgDir ($r.Key + '.svg')) -Value $svg -NoNewline
    [void]$readme.AppendLine("| ``$($r.Key).svg`` | $($r.Name) | $($r.Lib) | $($r.Lic) | $($r.Url) |")

    $log += ("{0,-18} {1,-14} {2,-26} {3,-12} {4,-8} {5} 字符" -f $r.Key, $r.Name, $r.Lib, $r.License, $(if ($stroked) { '描边' } else { '填充' }), $d.Length)
}

[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($true))

[void]$readme.AppendLine()
[void]$readme.AppendLine('许可证都是各家声明的（MIT / ISC / Apache-2.0），允许商用；')
[void]$readme.AppendLine('程序里要引用某一张时，在代码注释里带上库名 + 许可证即可。')
[System.IO.File]::WriteAllText((Join-Path $svgDir 'README.md'), $readme.ToString(), [System.Text.UTF8Encoding]::new($true))

Write-Host "已生成 $outFile 与 $svgDir（$($refs.Count) 支）"
$log | ForEach-Object { Write-Host "  $_" }
