<#
为「界面设计稿」出图工具准备图标路径，生成 tools/design-sheet/IconPaths.g.cs。

用法：
    pwsh tools/gen-ui-icons.ps1

和 tools/gen-fluent-icons.ps1 / gen-icons.ps1 同一套路：只从上游 SVG 里取
path 的 d 数据，不引入任何运行时代码；下载走 jsDelivr 镜像（国内直连
raw.githubusercontent.com 经常超时），并带本地缓存。

和那两支的区别：这张表是**探测式的**——每个位置给一串候选名，谁先下载到
就用谁，并且把「哪些候选名在上游根本不存在」打印出来。原因是 Fluent 的
命名不一定和我们的叫法一致（"荧光笔"是 Highlight 不是 Highlighter），
而这一轮的结论要能直接落到 src 里的图标表上，所以探测结果本身就是要留的证据。
#>

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$repoRoot = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $repoRoot 'tools/design-sheet/IconPaths.g.cs'
$cacheDir = Join-Path ([System.IO.Path]::GetTempPath()) 'fluent-icons'
New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null

$base = 'https://cdn.jsdelivr.net/gh/microsoft/fluentui-system-icons@main/assets'

# 本地名字 → 上游目录候选（按顺序试）。regular 变体，常态用。
$icons = [ordered]@{
    'mouse'       = @('Cursor', 'Arrow Mouse Cursor')
    'pen'         = @('Pen')
    'highlighter' = @('Highlight')
    'laser'       = @('Flash')
    'eraser'      = @('Eraser')
    'select'      = @('Select Object', 'Lasso')
    'lasso'       = @('Lasso')
    'shapes'      = @('Shapes')
    'capture'     = @('Screenshot', 'Camera')
    'undo'        = @('Arrow Undo')
    'redo'        = @('Arrow Redo')
    'settings'    = @('Settings')
    'lineWeight'  = @('Line Horizontal 1')
    'color'       = @('Color')
    'check'       = @('Checkmark')
    'more'        = @('More Horizontal')
    'dismiss'     = @('Dismiss')
    'board'       = @('Board', 'Whiteboard')
    'passthrough' = @('Eye Off')
    'delete'      = @('Delete')
    'chevronDown' = @('Chevron Down')
    'chevronRight'= @('Chevron Right')
    'pin'         = @('Pin')
    'square'      = @('Square')
    'circle'      = @('Circle')
    'triangle'    = @('Triangle')
    'arrowRight'  = @('Arrow Right')
    # 激光笔的几个候选（上游没有"激光笔"这个专名，只能从近义图标里挑）
    'laserFlash'      = @('Flash')
    'laserFlashlight' = @('Flashlight')
    'laserRecord'     = @('Record')
    'laserCircle'     = @('Circle')
    'laserTarget'     = @('Target')
    'laserWand'       = @('Wand')
    'laserSparkle'    = @('Sparkle')
    # 设置条右端那两个"动作"按钮
    'broom'           = @('Broom')
    'selectAll'       = @('Square Multiple')
}

# 激活态用的 filled 变体（Windows 11 的惯例：常态 regular、选中 filled）
$filledIcons = [ordered]@{
    'mouseFilled'       = @('Cursor')
    'penFilled'         = @('Pen')
    'highlighterFilled' = @('Highlight')
    'laserFilled'       = @('Flash')
    'laserRecordFilled' = @('Record')
    'eraserFilled'      = @('Eraser')
    'selectFilled'      = @('Select Object')
    'shapesFilled'      = @('Shapes')
    'captureFilled'     = @('Screenshot')
    'undoFilled'        = @('Arrow Undo')
    'redoFilled'        = @('Arrow Redo')
    'settingsFilled'    = @('Settings')
    'moreFilled'        = @('More Horizontal')
}

$used = @{}
$log = @()

function Get-UpstreamSvg([string]$folder, [string]$slug, [string]$variant) {
    $fileName = "ic_fluent_${slug}_24_${variant}.svg"
    $cache = Join-Path $cacheDir ($folder + '_' + $fileName)
    if (Test-Path $cache) { return Get-Content $cache -Raw }

    $url = "$base/" + [uri]::EscapeDataString($folder) + '/SVG/' + [uri]::EscapeDataString($fileName)
    try {
        $text = (Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 20).Content
    } catch {
        return $null
    }
    Set-Content -Path $cache -Value $text -NoNewline
    return $text
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('// 由 tools/gen-ui-icons.ps1 从微软官方图标库生成，请勿手改。')
[void]$sb.AppendLine('// 来源：https://github.com/microsoft/fluentui-system-icons （MIT License，')
[void]$sb.AppendLine('// Copyright (c) 2020 Microsoft Corporation）')
[void]$sb.AppendLine('// 两套变体都有：regular（常态）与 filled（激活态），viewBox 都是 0 0 24 24。')
[void]$sb.AppendLine('// 仅供「界面设计稿」出图工具使用，不进产品。')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace DesignSheet;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('internal static partial class IconPaths')
[void]$sb.AppendLine('{')

$allKeys = @()
foreach ($table in @(@($icons, 'regular'), @($filledIcons, 'filled'))) {
    $map = $table[0]; $variant = $table[1]
    foreach ($key in $map.Keys) {
        $found = $null; $foundName = $null
        foreach ($name in $map[$key]) {
            $slug = ($name -replace ' ', '_').ToLowerInvariant()
            $svg = Get-UpstreamSvg $name $slug $variant
            if ($svg) { $found = $svg; $foundName = $name; break }
        }
        if (-not $found) { throw "$key 的所有候选名都下载失败：$($map[$key] -join ', ')" }

        $m = [regex]::Matches($found, 'd="([^"]+)"')
        if ($m.Count -eq 0) { throw "$foundName 里没有找到路径数据" }
        $d = ($m | ForEach-Object { $_.Groups[1].Value }) -join ' '

        [void]$sb.AppendLine("    /// <summary>Fluent: $foundName (24 $variant)</summary>")
        [void]$sb.AppendLine("    public const string $key =")
        [void]$sb.AppendLine('        "' + $d + '";')
        [void]$sb.AppendLine()

        foreach ($ch in [regex]::Matches($d, '[A-Za-z]')) { $used[$ch.Value] = $true }
        $log += ("{0,-19} {1,-18} {2,-8} {3} 字符" -f $key, $foundName, $variant, $d.Length)
        $allKeys += $key
    }
}

[void]$sb.AppendLine('    /// <summary>按本地名字取路径数据（名字拼错时当场抛，别画出一个空图标）。</summary>')
[void]$sb.AppendLine('    public static string Get(string name) => name switch')
[void]$sb.AppendLine('    {')
foreach ($key in $allKeys) {
    [void]$sb.AppendLine('        "' + $key + '" => ' + $key + ',')
}
[void]$sb.AppendLine('        _ => throw new System.ArgumentOutOfRangeException(nameof(name), name, "图标表里没有这个名字"),')
[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($true))

Write-Host "已生成 $outFile"
$log | ForEach-Object { Write-Host "  $_" }
Write-Host ("出现过的 SVG 命令: " + (($used.Keys | Sort-Object) -join ' '))
