<#
从微软官方图标库抓取工具条要用的图标，生成 src/InkUi/FluentIcons.Paths.cs。

用法：
    pwsh tools/gen-fluent-icons.ps1

为什么走脚本而不是手工贴：
  1. 以后想换图标变体（比如改成 filled）只要改下面的表，不用手抄路径；
  2. 路径数据很长，手工复制容易漏字符，生成出来的东西可复现；
  3. 顺带把来源和许可证信息写进生成文件的头部。

图标库：https://github.com/microsoft/fluentui-system-icons （MIT License）
这里只取 SVG 里的路径数据，不引入它的任何运行时代码。
#>

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$repoRoot = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $repoRoot 'src/InkUi/FluentIcons.Paths.cs'
$cacheDir = Join-Path ([System.IO.Path]::GetTempPath()) 'fluent-icons'
New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null

# 用 jsDelivr 镜像：raw.githubusercontent.com 在国内网络下经常超时。
$base = 'https://cdn.jsdelivr.net/gh/microsoft/fluentui-system-icons@main/assets'

# 本地用的名字 → 上游图标目录
$icons = [ordered]@{
    'pen'         = 'Pen'
    'highlight'   = 'Highlight'
    'eraser'      = 'Eraser'
    'laser'       = 'Flash'
    'lineWeight'  = 'Line Horizontal 1'
    'color'       = 'Color'
    'undo'        = 'Arrow Undo'
    'delete'      = 'Delete'
    'check'       = 'Checkmark'
    'passthrough' = 'Eye Off'
    'whiteboard'  = 'Whiteboard'
}

function Get-UpstreamFile([string]$folder, [string]$fileName) {
    $cache = Join-Path $cacheDir ($folder + '_' + $fileName)
    if (Test-Path $cache) { return Get-Content $cache -Raw }

    $segments = @($folder, 'SVG', $fileName) | ForEach-Object { [uri]::EscapeDataString($_) }
    $url = "$base/" + ($segments -join '/')
    for ($attempt = 1; $attempt -le 4; $attempt++) {
        try {
            $text = (Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 25).Content
            Set-Content -Path $cache -Value $text -NoNewline
            return $text
        }
        catch {
            if ($attempt -eq 4) { throw "下载失败：$url`n$($_.Exception.Message)" }
            Start-Sleep -Seconds 2
        }
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('// 由 tools/gen-fluent-icons.ps1 从微软官方图标库生成，请勿手改。')
[void]$sb.AppendLine('// 来源：https://github.com/microsoft/fluentui-system-icons （MIT License，')
[void]$sb.AppendLine('// Copyright (c) 2020 Microsoft Corporation）')
[void]$sb.AppendLine('// 采用的是各图标的 24×24 regular 变体，viewBox 都是 0 0 24 24。')
[void]$sb.AppendLine('// 许可证全文见 src/InkUi/THIRD-PARTY-NOTICES.md。')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace InkUi;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('internal static partial class FluentIcons')
[void]$sb.AppendLine('{')

$count = 0
foreach ($key in $icons.Keys) {
    $folder = $icons[$key]
    # 文件名规则：目录名小写、空格换成下划线
    # 例：'Arrow Undo' -> ic_fluent_arrow_undo_24_regular.svg
    #     'Line Horizontal 1' -> ic_fluent_line_horizontal_1_24_regular.svg
    $slug = ($folder -replace ' ', '_').ToLowerInvariant()
    $fileName = "ic_fluent_${slug}_24_regular.svg"
    $svg = Get-UpstreamFile $folder $fileName

    $matches = [regex]::Matches($svg, 'd="([^"]+)"')
    if ($matches.Count -eq 0) { throw "$folder/$fileName 里没有找到路径数据" }
    $d = ($matches | ForEach-Object { $_.Groups[1].Value }) -join ' '

    [void]$sb.AppendLine("    /// <summary>$fileName</summary>")
    [void]$sb.AppendLine('    private const string Path_' + $key + ' =')
    [void]$sb.AppendLine('        "' + $d + '";')
    [void]$sb.AppendLine()
    $count++
}

[void]$sb.AppendLine('}')
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($true))
Write-Host "已生成 $outFile（$count 个图标）"
